const categories = [
  {name:'select', emoji:''},
  { name: 'Gaming', emoji: '🎮' },
  { name: 'Entertainment', emoji: '🎬' },
  { name: 'Music', emoji: '🎵' },
  { name: 'Development', emoji: '💻' },
  { name: 'Computers & Technology', emoji: '🖥️' },
  { name: 'AI & Machine Learning', emoji: '🤖' },
  { name: 'Movies & Film', emoji: '🎥' },
  { name: 'Fashion & Style', emoji: '👗' },
  { name: 'Food & Cooking', emoji: '🍲' },
  { name: 'Travel & Adventure', emoji: '🌍' },
  { name: 'Health & Wellness', emoji: '💪' },
  { name: 'Art & Design', emoji: '🎨' },
  { name: 'Literature & Writing', emoji: '📚' },
  { name: 'Sports & Athletics', emoji: '⚽' },
  { name: 'Science & Innovation', emoji: '🔬' },
  { name: 'Education & Learning', emoji: '📖' },
  { name: 'Business & Finance', emoji: '💼' },
  { name: 'Photography & Videography', emoji: '📷' },
  { name: 'DIY & Crafts', emoji: '🛠️' },
  { name: 'Family & Parenting', emoji: '👪' },
  { name: 'Environment & Sustainability', emoji: '🌱' },
  { name: 'Politics & Society', emoji: '🗳️' },
  { name: 'Beauty & Personal Care', emoji: '💄' },
  { name: 'Home & Lifestyle', emoji: '🏡' },
  { name: 'Automotive & Vehicles', emoji: '🚗' },
  { name: 'Pets & Animals', emoji: '🐾' },
  { name: 'Spirituality & Religion', emoji: '🙏' },
  { name: 'History & Culture', emoji: '🏛️' },
  { name: 'Language & Linguistics', emoji: '🗣️' },
  { name: 'Comedy & Humor', emoji: '😂' },
  { name: 'Documentary & Non-fiction', emoji: '📽️' },
  { name: 'Reaction & Review', emoji: '👀' },
  { name: 'Lifestyle & Vlogs', emoji: '💁' },
  { name: 'Technology & Gadgets', emoji: '📱' },
  { name: 'Gaming & eSports', emoji: '🎮' },
  { name: 'Fitness & Exercise', emoji: '💪' },
  { name: 'Fashion & Beauty Tips', emoji: '💅' },
  { name: 'Travel Guides & Tips', emoji: '🗺️' },
  { name: 'Health & Wellness Advice', emoji: '🍏' },
  { name: 'Art & Creativity Inspiration', emoji: '🎨' }
];

export default categories;